# -----------------------------------------------------------------
# الإصدار الذي يستخدمه docker-compose لتفسير هذا الملف. 3.8 هو إصدار حديث ومستقر.
version: '3.8'

# -----------------------------------------------------------------
# قسم "الخدمات". كل خدمة هي حاوية (container) في مشروعك.
# حالياً لدينا خدمة واحدة فقط، وهي قاعدة البيانات.
services:

  # -----------------------------------------------------------------
  # اسم خدمتنا. اخترت "mysql_db" ليكون واضحاً، لكن يمكنك تسميته أي شيء.
  mysql_db:
    # -----------------------------------------------------------------
    # "الصورة" (Image) التي ستُبنى منها الحاوية.
    # "mysql:8.0" تعني: اذهب إلى Docker Hub (مستودع الصور الرسمي)
    # وابحث عن الصورة الرسمية لـ MySQL، وحمّل الإصدار 8.0.
    image: mysql:8.0

    # -----------------------------------------------------------------
    # اسم مخصص للحاوية عند تشغيلها. هذا يسهل عليك العثور عليها
    # وإدارتها لاحقاً باستخدام أوامر Docker.
    container_name: expanders360-mysql

    # -----------------------------------------------------------------
    # سياسة إعادة التشغيل. "always" تعني أن Docker سيحاول دائماً
    # إعادة تشغيل هذه الحاوية إذا توقفت لأي سبب (مثل إعادة تشغيل الجهاز).
    restart: always

    # -----------------------------------------------------------------
    # "متغيرات البيئة" (Environment Variables). هذه هي الإعدادات التي نمررها
    # إلى MySQL عند بدء تشغيله لأول مرة.
    environment:
      # كلمة المرور الخاصة بالمستخدم "root" (المدير الأعلى لقاعدة البيانات).
      # يجب تغييرها إلى كلمة مرور قوية وحقيقية.
      MYSQL_ROOT_PASSWORD: eslambashry

      # اسم قاعدة البيانات التي تريد إنشاءها تلقائياً عند تشغيل الحاوية.
      # هذا يوفر عليك خطوة إنشاء قاعدة البيانات يدوياً.
      MYSQL_DATABASE: expanders360_db

      # اسم مستخدم جديد مخصص لتطبيقك (أكثر أماناً من استخدام root).
      MYSQL_USER: user

      # كلمة المرور الخاصة بالمستخدم الجديد.
      MYSQL_PASSWORD: eslambashry

    # -----------------------------------------------------------------
    # "المنافذ" (Ports). هذا الجزء مهم جداً للاتصال بالحاوية.
    # يقوم بربط منفذ على جهازك (Host) بمنفذ داخل الحاوية (Container).
    # "3306:3306" تعني:
    # - أي اتصال يأتي إلى المنفذ 3306 على جهازك (localhost:3306)
    # - سيتم توجيهه إلى المنفذ 3306 داخل حاوية MySQL.
    ports:
      - "3306:3306"

    # -----------------------------------------------------------------
    # "المجلدات" (Volumes). هذا الجزء يحل مشكلة فقدان البيانات.
    # بشكل افتراضي، إذا حذفت الحاوية، ستُحذف بياناتها معها.
    # هذا السطر يخبر Docker بربط مجلد داخل الحاوية (/var/lib/mysql)
    # بمجلد مُدار بواسطة Docker على جهازك اسمه "mysql_data".
    # بهذا، حتى لو حذفت الحاوية وأعدت بناءها، ستبقى بياناتك محفوظة.
    volumes:
      - mysql_data:/var/lib/mysql

# -----------------------------------------------------------------
# تعريف المجلدات المُدارة بواسطة Docker التي ذكرناها أعلاه.
volumes:
  mysql_data:
